// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCudDpWYFkrcnK4V4g5icvtHC1k8vXqUII',
    appId: '1:281171118004:web:739ff2b1d89ec2406cd4e1',
    messagingSenderId: '281171118004',
    projectId: 'notepad-2b8ea',
    authDomain: 'notepad-2b8ea.firebaseapp.com',
    storageBucket: 'notepad-2b8ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrznyY92gHQfgPA5GIkRJmpLmCCqtXmUk',
    appId: '1:281171118004:android:bdd2fbd4ba0f48a96cd4e1',
    messagingSenderId: '281171118004',
    projectId: 'notepad-2b8ea',
    storageBucket: 'notepad-2b8ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhi5yO5pRjBlVs39-Wr-eUeEMYZGcnxpg',
    appId: '1:281171118004:ios:4020af821c6711f66cd4e1',
    messagingSenderId: '281171118004',
    projectId: 'notepad-2b8ea',
    storageBucket: 'notepad-2b8ea.appspot.com',
    iosClientId: '281171118004-6brqjbr4qfmipd99i6sf293j7l60ebfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.notepadClone',
  );
}
